<img src="https://www.who.int//images/default-source/infographics/who-emblem.png" width="100" align="left">

# Querying WHO Data
    


## This data is obtained from the GHO (Global Health Observatory)

### Debido a la gran cantidad de información de salud contenida en el Observatorio de la WHO vamos a seguir algunos pasos para segmentar las consultas hacia el API

In [29]:
#Librerias 
import pandas as pd
import requests
from IPython.display import display

### 1. Consultar las *Dimensiones* disponibles

In [200]:
#Datos del conexion al API
url_dimensiones = "http://apps.who.int/gho/athena/api/"
parametros = {'format': 'json'}

#LLamado del API
response_dim = requests.get(url_dimensiones,params=parametros)
datos_dimensiones = response_dim.json()

#Construccion DF Pandas
df_dimensiones=pd.DataFrame(datos_dimensiones["dataset"])

#Render del combo de seleccion
ddl_dimension = widgets.Dropdown(options=df_dimensiones["display"])
display(ddl_dimension)

Dropdown(options=('COUNTRY_YEARLY_CORE_UNITS', 'COUNTRY_YEARLY_BASIC_DATA', 'COUNTRY_YEARLY_LIFE_MEASURES', 'R…

### 2. Consultar los codigos disponibles para las  *Dimensiónes*

In [450]:
def extract_cat(lista_cat):
    df_tmp = pd.DataFrame(lista_cat)
    df_tmp_1 = df_tmp.get("category",default="no_category")
    if df_tmp_1[0] == "CATEGORY":
        print(df_tmp["category"])
    #    df_tmp_2 = df_tmp[df_tmp["category"] == "CATEGORY"]["value"].tolist()[0]
    #    return str(df_tmp_2)

In [451]:
#Se recuperan el codigo de la dimension
dimension_code = list(df_dimensiones[df_dimensiones["display"] == ddl_dimension.value]["label"])

#Datos del conexion al API
url_datos_dimension = "http://apps.who.int/gho/athena/api/GHO"
parametros = {'format': 'json'}

#LLamado del API
response_datos_dimension = requests.get(url_datos_dimension,params=parametros)
datos_dimension = response_datos_dimension.json()


#Construccion DF Pandas
df_atribute = pd.DataFrame(datos_dimension["attribute"])

df_codes =pd.DataFrame(datos_dimension["dimension"][0]["code"])
#df_codes["category"] = 
x=df_codes["attr"].map(extract_cat)
x
#df_codes   
#Render del combo de seleccion
#ddl_datos_dimension = widgets.Dropdown(options=df_datos_dimension['Code'])
#display(ddl_datos_dimension)

0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1            IMR_ID
2    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
2            IMR_ID
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
2            IMR_ID
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
2            IMR_ID
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
2            IMR_ID
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
2            IMR_ID
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
2            IMR_ID
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
2            IMR_ID
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
2            IMR_ID
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
2            IMR_ID
Name: category, dtype: object
0          CATEGORY
1            IMR_ID
2    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
2            IMR_ID
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
2            IMR_ID
Name: category, dtype: object
0          CATEGORY
1            IMR_ID
2    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML

Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1            IMR_ID
2    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1            IMR_ID
2    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1            IMR_ID
2    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY

Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1            IMR_ID
2    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1            IMR_ID
2    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
2            IMR_ID
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
2            IMR_ID
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
2            IMR_ID
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
2            IMR_ID
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
2            IMR_ID
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object

0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML

Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
2            IMR_ID
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
2            IMR_ID
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
2            IMR_ID
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
2            IMR_ID
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
2            IMR_ID
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
2            IMR_ID
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
2            IMR_ID
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
2            IMR_ID
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
2            IMR_ID
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
2            IMR_ID
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
2            IMR_ID
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
2            IMR_ID
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
2            IMR_ID
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
2            IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID

Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0          CATEGORY
1            IMR_ID
2    DEFINITION_XML
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
2            IMR_ID
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
2            IMR_ID
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object

0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
1      IMR_ID
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY

Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0          CATEGORY
1    DEFINITION_XML
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object
0    CATEGORY
Name: category, dtype: object

0       None
1       None
2       None
3       None
4       None
        ...
2861    None
2862    None
2863    None
2864    None
2865    None
Name: attr, Length: 2866, dtype: object

### 3. Consultar las lista de *Indicadores* disponibles

In [175]:
#Datos del conexion al API
url_indicadores = "https://ghoapi.azureedge.net/api/Indicator"

#LLamado del API
response_indicadores = requests.get(url_indicadores)
datos_indicadores = response_indicadores.json()

#Construccion DF Pandas
df_datos_indicadores = pd.DataFrame(datos_indicadores["value"])
df_datos_indicadores = df_datos_indicadores.sort_values(by=["IndicatorName"])

#Render del combo de seleccion
ddl_datos_indicadores = widgets.Dropdown(options=df_datos_indicadores["IndicatorName"])
display(ddl_datos_indicadores)

Dropdown(options=('13-15-years old any alcoholic beverage consumed in past 30 days, (%)', '13-15-years old any…

In [176]:
#Codigo del Indicador
indicator_code = list(df_datos_indicadores[df_datos_indicadores["IndicatorName"] == ddl_datos_indicadores.value]["IndicatorCode"])

#Datos del conexion al API
url_indicador = f"https://ghoapi.azureedge.net/api/{indicator_code[0]}"
url_indicador

#LLamado del API
esponse_indicador = requests.get(url_indicador)
datos_indicador = response_indicador.json()

#Construccion DF Pandas
df_datos_indicador = pd.DataFrame(datos_indicador["value"])
df_datos_indicador

,Id,IndicatorCode,SpatialDimType,SpatialDim,TimeDimType,TimeDim,Dim1Type,Dim1,Dim2Type,Dim2,...,DataSourceDim,Value,NumericValue,Low,High,Comments,Date,TimeDimensionValue,TimeDimensionBegin,TimeDimensionEnd
0,19838948,SA_0000001807,COUNTRY,ZAF,YEAR,2016,SEX,FMLE,None,None,...,None,143.8,None,None,None,None,2018-09-06T10:03:07.143+02:00,2016,2016-01-01T00:00:00+01:00,2016-12-31T00:00:00+01:00
1,19838949,SA_0000001807,COUNTRY,ZWE,YEAR,2016,SEX,FMLE,None,None,...,None,146.8,None,None,None,None,2018-09-06T10:03:07.167+02:00,2016,2016-01-01T00:00:00+01:00,2016-12-31T00:00:00+01:00
2,19838950,SA_0000001807,COUNTRY,AGO,YEAR,2016,SEX,MLE,None,None,...,None,112.5,None,None,None,None,2018-09-06T10:03:07.187+02:00,2016,2016-01-01T00:00:00+01:00,2016-12-31T00:00:00+01:00
3,19838951,SA_0000001807,COUNTRY,CAF,YEAR,2016,SEX,MLE,None,None,...,None,141.4,None,None,None,None,2018-09-06T10:03:07.207+02:00,2016,2016-01-01T00:00:00+01:00,2016-12-31T00:00:00+01:00
4,19838952,SA_0000001807,COUNTRY,ERI,YEAR,2016,SEX,MLE,None,None,...,None,109.3,None,None,None,None,2018-09-06T10:03:07.233+02:00,2016,2016-01-01T00:00:00+01:00,2016-12-31T00:00:00+01:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
383,19845156,SA_0000001807,COUNTRY,NRU,YEAR,2016,SEX,MLE,None,None,...,None,No data,None,None,None,None,2018-09-06T10:05:19.07+02:00,2016,2016-01-01T00:00:00+01:00,2016-12-31T00:00:00+01:00
384,19845157,SA_0000001807,COUNTRY,AUS,YEAR,2016,SEX,FMLE,None,None,...,None,118.9,None,None,None,None,2018-09-06T10:05:19.1+02:00,2016,2016-01-01T00:00:00+01:00,2016-12-31T00:00:00+01:00
385,19845158,SA_0000001807,COUNTRY,KHM,YEAR,2016,SEX,FMLE,None,None,...,None,145.1,None,None,None,None,2018-09-06T10:05:19.123+02:00,2016,2016-01-01T00:00:00+01:00,2016-12-31T00:00:00+01:00
386,19845159,SA_0000001807,COUNTRY,PNG,YEAR,2016,SEX,FMLE,None,None,...,None,186.5,None,None,None,None,2018-09-06T10:05:19.15+02:00,2016,2016-01-01T00:00:00+01:00,2016-12-31T00:00:00+01:00
387,19845160,SA_0000001807,COUNTRY,KOR,YEAR,2016,SEX,FMLE,None,None,...,None,91.2,None,None,None,None,2018-09-06T10:05:19.17+02:00,2016,2016-01-01T00:00:00+01:00,2016-12-31T00:00:00+01:00

In [170]:
df_datos_indicador[df_datos_indicador["SpatialDim"]==ddl_datos_dimension.value]

,Id,IndicatorCode,SpatialDimType,SpatialDim,TimeDimType,TimeDim,Dim1Type,Dim1,Dim2Type,Dim2,...,DataSourceDim,Value,NumericValue,Low,High,Comments,Date,TimeDimensionValue,TimeDimensionBegin,TimeDimensionEnd
145,19840858,SA_0000001807,COUNTRY,COL,YEAR,2016,SEX,FMLE,None,None,...,None,147.4,None,None,None,None,2018-09-06T10:03:49.873+02:00,2016,2016-01-01T00:00:00+01:00,2016-12-31T00:00:00+01:00
147,19840928,SA_0000001807,COUNTRY,COL,YEAR,2016,SEX,MLE,None,None,...,None,180,None,None,None,None,2018-09-06T10:03:51.43+02:00,2016,2016-01-01T00:00:00+01:00,2016-12-31T00:00:00+01:00